/*
  This file is auto-generated by 'npm run genabi'  
  Do not edit manually - changes will be overwritten
  
  Contract: CipherLink
  Generated: 2025-10-29T07:23:09.021Z
*/

export const CipherLinkAddresses = {
  "11155111": { 
    address: "0x43c9880fCbA23f4d0acd191991bA5AA03471fF44" as const, 
    chainId: 11155111, 
    chainName: "sepolia" 
  },
  "31337": { 
    address: "0x43c9880fCbA23f4d0acd191991bA5AA03471fF44" as const, 
    chainId: 31337, 
    chainName: "hardhat" 
  },
} as const;

export type CipherLinkAddresses = typeof CipherLinkAddresses;

// Helper to get contract address by chain ID
export function getCipherLinkAddress(chainId: number): string {
  const key = chainId.toString() as keyof typeof CipherLinkAddresses;
  const deployment = CipherLinkAddresses[key];
  
  if (!deployment) {
    throw new Error(`CipherLink not deployed on chain ${chainId}`);
  }
  
  return deployment.address;
}

// Supported chain IDs
export const SUPPORTED_CHAIN_IDS = [31337, 11155111] as const;
